# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drones.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64rones.proto\"\x07\n\x05\x45mpty\"#\n\x13RegistrationRequest\x12\x0c\n\x04name\x18\x01 \x01(\x05\"\"\n\x14RegistrationResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1d\n\x0fWaypointRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"7\n\x10WaypointResponse\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\"#\n\x0fPositionRequest\x12\x10\n\x08position\x18\x01 \x03(\x02\"\"\n\x10PositionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb8\x01\n\x07Greeter\x12\x39\n\x08register\x12\x14.RegistrationRequest\x1a\x15.RegistrationResponse\"\x00\x12\x38\n\x0flisten_waypoint\x12\x10.WaypointRequest\x1a\x11.WaypointResponse\"\x00\x12\x38\n\rsend_position\x12\x10.PositionRequest\x1a\x11.PositionResponse\"\x00(\x01\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_REGISTRATIONREQUEST = DESCRIPTOR.message_types_by_name['RegistrationRequest']
_REGISTRATIONRESPONSE = DESCRIPTOR.message_types_by_name['RegistrationResponse']
_WAYPOINTREQUEST = DESCRIPTOR.message_types_by_name['WaypointRequest']
_WAYPOINTRESPONSE = DESCRIPTOR.message_types_by_name['WaypointResponse']
_POSITIONREQUEST = DESCRIPTOR.message_types_by_name['PositionRequest']
_POSITIONRESPONSE = DESCRIPTOR.message_types_by_name['PositionResponse']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

RegistrationRequest = _reflection.GeneratedProtocolMessageType('RegistrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONREQUEST,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:RegistrationRequest)
  })
_sym_db.RegisterMessage(RegistrationRequest)

RegistrationResponse = _reflection.GeneratedProtocolMessageType('RegistrationResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONRESPONSE,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:RegistrationResponse)
  })
_sym_db.RegisterMessage(RegistrationResponse)

WaypointRequest = _reflection.GeneratedProtocolMessageType('WaypointRequest', (_message.Message,), {
  'DESCRIPTOR' : _WAYPOINTREQUEST,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:WaypointRequest)
  })
_sym_db.RegisterMessage(WaypointRequest)

WaypointResponse = _reflection.GeneratedProtocolMessageType('WaypointResponse', (_message.Message,), {
  'DESCRIPTOR' : _WAYPOINTRESPONSE,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:WaypointResponse)
  })
_sym_db.RegisterMessage(WaypointResponse)

PositionRequest = _reflection.GeneratedProtocolMessageType('PositionRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONREQUEST,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:PositionRequest)
  })
_sym_db.RegisterMessage(PositionRequest)

PositionResponse = _reflection.GeneratedProtocolMessageType('PositionResponse', (_message.Message,), {
  'DESCRIPTOR' : _POSITIONRESPONSE,
  '__module__' : 'drones_pb2'
  # @@protoc_insertion_point(class_scope:PositionResponse)
  })
_sym_db.RegisterMessage(PositionResponse)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=16
  _EMPTY._serialized_end=23
  _REGISTRATIONREQUEST._serialized_start=25
  _REGISTRATIONREQUEST._serialized_end=60
  _REGISTRATIONRESPONSE._serialized_start=62
  _REGISTRATIONRESPONSE._serialized_end=96
  _WAYPOINTREQUEST._serialized_start=98
  _WAYPOINTREQUEST._serialized_end=127
  _WAYPOINTRESPONSE._serialized_start=129
  _WAYPOINTRESPONSE._serialized_end=184
  _POSITIONREQUEST._serialized_start=186
  _POSITIONREQUEST._serialized_end=221
  _POSITIONRESPONSE._serialized_start=223
  _POSITIONRESPONSE._serialized_end=257
  _GREETER._serialized_start=260
  _GREETER._serialized_end=444
# @@protoc_insertion_point(module_scope)
