# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import drones_pb2 as drones__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/Greeter/register',
                request_serializer=drones__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=drones__pb2.RegistrationResponse.FromString,
                )
        self.listen_waypoint = channel.unary_unary(
                '/Greeter/listen_waypoint',
                request_serializer=drones__pb2.WaypointRequest.SerializeToString,
                response_deserializer=drones__pb2.WaypointResponse.FromString,
                )
        self.send_position = channel.stream_unary(
                '/Greeter/send_position',
                request_serializer=drones__pb2.PositionRequest.SerializeToString,
                response_deserializer=drones__pb2.PositionResponse.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register(self, request, context):
        """Registers the drone to ground-station
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listen_waypoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send_position(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=drones__pb2.RegistrationRequest.FromString,
                    response_serializer=drones__pb2.RegistrationResponse.SerializeToString,
            ),
            'listen_waypoint': grpc.unary_unary_rpc_method_handler(
                    servicer.listen_waypoint,
                    request_deserializer=drones__pb2.WaypointRequest.FromString,
                    response_serializer=drones__pb2.WaypointResponse.SerializeToString,
            ),
            'send_position': grpc.stream_unary_rpc_method_handler(
                    servicer.send_position,
                    request_deserializer=drones__pb2.PositionRequest.FromString,
                    response_serializer=drones__pb2.PositionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/register',
            drones__pb2.RegistrationRequest.SerializeToString,
            drones__pb2.RegistrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def listen_waypoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/listen_waypoint',
            drones__pb2.WaypointRequest.SerializeToString,
            drones__pb2.WaypointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def send_position(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Greeter/send_position',
            drones__pb2.PositionRequest.SerializeToString,
            drones__pb2.PositionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
